#!/bin/bash
#SBATCH --job-name=EC-12_files --output=z01.%x
#SBATCH --mail-type=END,FAIL --mail-user=hsw33@georgetown.edu
#SBATCH --nodes=1 --ntasks=1 --cpus-per-task=1 --time=72:00:00
#SBATCH --mem=4G

#---Set environment---#
shopt -s expand_aliases
module load trimmomatic

#---Define variables with file locations---#
#adapters=/home/hsw33/TruSeq3-PE.fa

#input_R1=/home/hsw33/WTA2_1.fq.gz
#input_R2=/home/hsw33/WTA2_2.fq.gz

#output_R2_PE=/home/hsw33/WTA2_1.trPE.fastq.gz
#output_R2_SE=/home/hsw33/WTA2_2.trSE.fastq.gz

#---Run command---#
trimmomatic PE \
WTA2_1.fq.gz \
WTA2_2.fq.gz \
output_WTA2_1_pairedend_SC1.fq.gz output_WTA2_1_singleend.fq.gz \
output_WTA2_2_pairedend_SC1.fq.gz output_WTA2_2_singleend.fq.gz \
ILLUMINACLIP:TruSeq3-PE.fa:2:30:10 \
HEADCROP:15 \
TRAILING:20 \
SLIDINGWINDOW:4:15 \
MINLEN:75
